#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/s5e8825-common

PRODUCT_COPY_FILES += \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/SoundBoosterParam.txt:$(TARGET_COPY_OUT_VENDOR)/etc/SoundBoosterParam.txt \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/eden/gpu/eden_kernel_64.bin:$(TARGET_COPY_OUT_VENDOR)/etc/eden/gpu/eden_kernel_64.bin \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/gnss/ca.pem:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/ca.pem \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/gnss/gps.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.cfg \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/init/android.hardware.drm-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.widevine.rc \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.samsung.rc \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/init/init.nfc.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.nfc.samsung.rc \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/init/secaudiohalaidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/secaudiohalaidl.rc \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/init/teegris_v4.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/teegris_v4.rc \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/init/vendor.samsung.hardware.gnss@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.gnss@2.1-service.rc \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/init/vendor.samsung.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rild.rc \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/init/wifi_slsi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi_slsi.rc \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/media_codecs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs.xml \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/media_codecs_performance.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance.xml \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/mixer_usb_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_usb_default.xml \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/mixer_usb_gray.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_usb_gray.xml \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/mixer_usb_white.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_usb_white.xml \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/mtu-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtu-conf.xml \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/plmn_delta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta.bin \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/plmn_delta_chn.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_chn.bin \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/plmn_delta_hktw.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_hktw.bin \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/plmn_se13_prebuilt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_se13_prebuilt.bin \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/sec_audio_volume_curve.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sec_audio_volume_curve.xml \
    vendor/samsung/s5e8825-common/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/samsung/s5e8825-common/proprietary/vendor/firmware/APSV_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APSV_AUDIO_SLSI.bin \
    vendor/samsung/s5e8825-common/proprietary/vendor/firmware/OD_V2.1.6_01_26_QVGA.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V2.1.6_01_26_QVGA.nnc \
    vendor/samsung/s5e8825-common/proprietary/vendor/firmware/OD_V2.3.7_02_05_VGA.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V2.3.7_02_05_VGA.nnc \
    vendor/samsung/s5e8825-common/proprietary/vendor/firmware/avsyncmix.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/avsyncmix.bin \
    vendor/samsung/s5e8825-common/proprietary/vendor/firmware/bidirmic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bidirmic.bin \
    vendor/samsung/s5e8825-common/proprietary/vendor/firmware/dax_param.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dax_param.bin \
    vendor/samsung/s5e8825-common/proprietary/vendor/firmware/default_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/default_configuration.flm.cfg.bin \
    vendor/samsung/s5e8825-common/proprietary/vendor/firmware/dolby.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dolby.bin \
    vendor/samsung/s5e8825-common/proprietary/vendor/firmware/listenbackeffect.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/listenbackeffect.bin \
    vendor/samsung/s5e8825-common/proprietary/vendor/firmware/secure_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/secure_configuration.flm.cfg.bin \
    vendor/samsung/s5e8825-common/proprietary/vendor/firmware/volumemonitor.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/volumemonitor.bin \
    vendor/samsung/s5e8825-common/proprietary/vendor/firmware/wifi/mx140.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140.bin \
    vendor/samsung/s5e8825-common/proprietary/vendor/firmware/wifi/mx140_t.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_t.bin \
    vendor/samsung/s5e8825-common/proprietary/vendor/firmware/wifi/mx140_t_common.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_t_common.hcf

PRODUCT_PACKAGES += \
    libGLES_mali \
    android.hardware.gnss@2.1-impl \
    audio.primary.s5e8825 \
    audio.sec_primary.default \
    gatekeeper.s5e8825 \
    libsecaudiohal_aidl \
    vendor.samsung.hardware.gnss@2.1-impl \
    vulkan.mali \
    libSEF.quram \
    libSamsungPostProcessConvertor \
    libVendorSemDataProps \
    libVendorSemTelephonyProps \
    lib_SamsungRec_07010 \
    lib_SoundAlive_SRC384_ver320 \
    lib_soundaliveresampler \
    libaboxpcmdump \
    libalsautils_sec \
    libaudio-ril \
    libaudioparamupdate \
    libaudioproxy2 \
    libaudioroute.s5e8825 \
    libc++_shared \
    libcommon \
    libcommon_graphgen_export \
    libcrane_compiler \
    libcrypto-tm \
    libdatamod \
    libdove_compiler \
    libeden_model \
    libeden_nn \
    libeden_osal \
    libeden_profiler \
    libeden_rt \
    libeden_ud_cpu \
    libeden_ud_dsp \
    libeden_ud_gpu \
    libeden_ud_npu \
    libeden_xtool \
    libegis_fp_normal_sensor_test \
    libengmode_client \
    libenn_dsp_dal \
    libenn_dsp_fw_graph_parser \
    libenn_dsp_kernels_cpu \
    libexynoscamera_cnr_plugin \
    libexynoscamera_plugin \
    libfloatingfeature \
    libgf_in_system_lib \
    libgraphgen_ann_import \
    libgraphgen_ann_import_s \
    libgraphgen_ann_nnc \
    libgraphgen_api \
    libgraphgen_export \
    libgraphgen_import \
    libgraphgen_intermediate_process \
    libgraphgen_misc \
    libgraphgen_network \
    libhwjsqz \
    libir \
    liblastaboxmsg \
    libnpu_compiler \
    libnpuc_api \
    libnpuc_backend \
    libnpuc_cmdq \
    libnpuc_common \
    libnpuc_controller \
    libnpuc_frontend \
    libnpuc_graph \
    libnpuc_template \
    liboemcrypto \
    libprofileparamstorage \
    libqfp_sensortest \
    librecordalive \
    libril_sem \
    libsait_npu_compiler \
    libsec-ril \
    libsecaudiocoreutils \
    libsecaudioinfo \
    libsecaudiolevel \
    libsecnativefeature \
    libsecril-client \
    libsehbluetooth_audio_session_aidl \
    libsemnativecarrierfeature \
    libsensorlistener \
    libskeymint10device \
    libskeymint_cli \
    libspatializerparamstorage \
    libspeakercalibration \
    libswcnr \
    libsynaFpSensorTestNwd \
    libteecl \
    libtinyalsa.s5e8825 \
    libtoco_graphgen_export \
    libuniapi \
    libuniplugin \
    libuuid_vendor \
    libvkmanager_vendor \
    libvpl \
    libwrappergps \
    libwvaidl \
    sensors.grip \
    sensors.inputvirtual \
    sensors.sensorhub \
    libswdap \
    vendor.samsung.hardware.audio-V1-ndk \
    vendor.samsung.hardware.bluetooth.audio-V1-ndk \
    vendor.samsung.hardware.gnss@2.0 \
    vendor.samsung.hardware.gnss@2.1 \
    vendor.samsung.hardware.keymint-V1-ndk_platform \
    vendor.samsung.hardware.radio-V1-ndk \
    vendor.samsung.hardware.radio.bridge-V1-ndk \
    vendor.samsung.hardware.radio.channel-V1-ndk \
    vendor.samsung.hardware.radio.data-V1-ndk \
    vendor.samsung.hardware.radio.messaging-V1-ndk \
    vendor.samsung.hardware.radio.sim-V1-ndk \
    vendor.samsung.hardware.thermal@1.0 \
    manifest_android.hardware.drm-service.widevine.xml \
    secaudiohalaidl_manifest.xml \
    vendor.samsung.hardware.radio.exclude.slsi.xml \
    vendor.samsung.hardware.radio_manifest_2_34.xml \
    vendor.samsung.hardware.sehradio_manifest_2_34.xml \
    android.hardware.drm-service.widevine \
    android.hardware.security.keymint-service.samsung \
    gps \
    gpsd \
    rild \
    secaudiohalaidl \
    vendor.samsung.hardware.gnss@2.1-service \
    tzdaemon \
    tzts_daemon

PRODUCT_PACKAGES += \
    vendor_lib64_libOpenCL_so \
    vendor_lib64_libOpenCL_so_1 \
    vendor_lib64_libOpenCL_so_1_1
